sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - g++-8

before_install:
  - pip install --user cpp-coveralls
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false